Wdp210302 11
kstobiecki/WDP-2103-02 pull request #11
Opened 2021-03-19 00:59 UTC by mssbase

- dodawanie funkcjonalności guzika ulubione
- po odświeżeniu strony przynajmniej jeden guzik jest aktywny

nie jestem pewny czy ten guzik ma się odklikiwać czy nie ?

2021-03-21 12:24 UTC, kstobiecki requested changes
![image](https://user-images.githubusercontent.com/33237579/111904706-88a93100-8a48-11eb-88fe-8987c84b7631.png)
Nie ma możliwości klikania i odklikania ulubionego produktu

2021-03-22 12:43 UTC, mssbase commented
już powinny się klikać coś było namieszane . zaraz zrobię odklikiwanie

2021-03-22 14:13 UTC, mssbase commented
ulubione się klikaj i odklikują

2021-03-22 14:29 UTC, kstobiecki requested changes
Almost. After clicking the love button user should't be redirect. You need to implement event.preventDefault() when clicking in a tag

2021-03-22 15:30 UTC, mssbase commented
dodany preventdefault

2021-03-23 10:47 UTC, kstobiecki approved these changes

2021-03-23 10:47 UTC, merged