WDP210302-33
kstobiecki/WDP-2103-02 pull request #27
Opened 2021-03-26 22:10 UTC by AsiaZmudziak

2021-03-27 14:45 UTC, kstobiecki requested changes

2021-03-27 14:45 UTC, kstobiecki commented on src/components/features/Feedback/Feedback.js
> +  handlePageChange = newPage => {
potrzebujemy handlePageChange w tym komponencie? Miał być on póki co statyczny

2021-03-27 21:06 UTC, AsiaZmudziak commented on src/components/features/Feedback/Feedback.js
> +  handlePageChange = newPage => {
przepraszam. nie wyczyściłam kodu. Funkcjonalność tej sekcji też jest po mojej stronie.

2021-03-28 12:33 UTC, kstobiecki approved these changes

2021-03-28 12:33 UTC, merged